### PR TITLE
Building and running tests with Maven

### PR DESCRIPTION
**Pull request by RodionGork**
Hi Friends!

I dare to suggest this `pom.xml` which uses kotlin-maven-plugin to allow building the exercises and testing them with maven (as another option in addition to having idea / eclipse project files).

### CODE REVIEW

**Comment by fwilhe** [comment]
What is the status of this PR? I think the commits that solve the koans should not be included here, but I support having the `pom.xml` in master (did not test if it works).

Will this be merged into master eventually?

**Comment by svtk** [comment]
Hi all! 
@RodionGork thank you for your pull request.
@RodionGork, @fwilhe Why do you want to have this project built with maven?

I'm afraid having two options for being built is not a good idea, because we could end up with two different versions of Kotlin: one from maven, another from plugin. I could change and build the project with maven by default, but I'm not sure whether everyone will prefer this way. Currently you have to know nothing about maven to solve tasks, that might be good for some people.

**Comment by svtk** [comment]
I'm closing this pull-request for now. However, we can discuss building the project with maven. If necessary the changes can be easily made.

**Comment by fwilhe** [comment]
Hi @svtk,

I don't consider relying on the IntelliJ-plugin good practice. Maven (and also gradle) are the defacto-standards for java projects, and from my experience it works quite well with Kotlin and with the IntelliJ-plugin. I would generally prefer a stronger focus on those tools that all Java developers know by the Kotlin team. I think this would make it easier to convince Java developers to switch to Kotlin.

**Comment by yole** [comment]
Maven and Gradle are de-facto standards for Java projects. Koans are not a project, they're a playground; they do not benefit from any advantages that Maven and Gradle bring to real projects. Also, the target audience of koans includes novice developers that have no experience with using any of the tools that all experienced Java developers know.

**Comment by abelsromero** [comment]
> Also, the target audience of koans includes novice developers that have no experience with using any of the tools that all experienced Java developers know.

@yole I don't fully agree with that. While is true that the project should be really easy to use for any level of expertise, I think it also should be independent of the IDE or tool the developer wants to use and not force to an specific IDE. In my expierience usually the first tool to use is Java is Eclipse, but nowadays more and more people use tools like Atom or Brackets. Isn't Kotlin aiming for the web also with a JS compiler? Does not then make sense to allow the use of something like the last tools mentioned?

If the answer is yes, I think that using a building tool is the way to go, and going into more detail, Gradle can be easily be set to easily allow execution from IDEs or command line with 0 knownledge.
The Wrapper and some custom tasks can get the job done, for instance, Groovy koans get that done quite nicely https://github.com/nadavc/groovykoans.

**Comment by yole** [comment]
@abelsromero Tooling is a major part of Kotlin, and we invest in building tools that run in IDEA (first and foremost) and Eclipse (secondary). Therefore, we need to drive beginner developers towards those tools, show them that they exist, and teach them how to use them. Pretending that people using Atom or Brackets will get the same level of productivity when using Kotlin as people using IntelliJ IDEA will not do anyone any service.

**Pull request closed without merging**
